In [2]:
# matrices in numpy and operations on them
import numpy as np
# matrix = 2d array, array of array
M = np.array([[1,2],[3,4]])
M

array([[1, 2],
       [3, 4]])

In [3]:
M[0][0]

1

In [4]:
M[0,0]

1

In [5]:
M.T

array([[1, 3],
       [2, 4]])

In [8]:
M

array([[1, 2],
       [3, 4]])

In [4]:
M*M # does element wise multiplication

array([[ 1,  4],
       [ 9, 16]])

In [6]:
np.dot(M,M) # matrix multiplication

array([[ 7, 10],
       [15, 22]])

In [7]:
# Matrix inverse
M_inv = np.linalg.inv(M)
np.dot(M, M_inv)

array([[1.00000000e+00, 1.11022302e-16],
       [0.00000000e+00, 1.00000000e+00]])

In [9]:
# solving equations
a = np.array([[1,2],[3,4]])
b = np.array([1,2])
x = np.dot(np.linalg.inv(a),b)
x

array([2.22044605e-16, 5.00000000e-01])

In [10]:
np.dot(a,x)

array([1., 2.])

In [12]:
# or, use solve
y = np.linalg.solve(a,b)
y

array([0. , 0.5])

In [13]:
np.dot(a,y)

array([1., 2.])

In [14]:
A = np.array([[1,1],[1.5,4]])
b = np.array([2200,5050])
x = np.linalg.solve(A,b)
x

array([1500.,  700.])