In [17]:
import numpy as np

# understand difference between lists and numpy arrays

L = [1,2,3]
A = np.array([1,2,3])

In [10]:
# loop through list
for e in L:
    print(e)

1
2
3


In [11]:
# loop through array
for e in A:
    print(e)

1
2
3


In [18]:
# append to lists:
L.append(4)
L

[1, 2, 3, 4]

In [19]:
# append to arrays:
A.append(4) # will throw an error because this is not possible with arrays

AttributeError: 'numpy.ndarray' object has no attribute 'append'

In [20]:
# we can't add elements to a numpy array
L = L + [5]
L

[1, 2, 3, 4, 5]

In [21]:
A = A + [4,5]

ValueError: operands could not be broadcast together with shapes (3,) (2,) 

In [22]:
# add two lists
L2 = []
for e in L:
    L2.append(e+e)
L2

[2, 4, 6, 8, 10]

In [23]:
# same operation with arrays
A = A + A
A

# Lesson 1: plus in lists does concatenation, + in numpy array does vector addition

array([2, 4, 6])

In [24]:
# multiply elements of matrix with a constant
A = 2 * A
A

array([ 4,  8, 12])

In [25]:
# but the same command doesnt work with lists
2*L

[1, 2, 3, 4, 5, 1, 2, 3, 4, 5]

In [27]:
# try squaring each element in a list and array
l2 = []

for e in L:
    l2.append(e**2)
l2

[1, 4, 9, 16, 25]

In [28]:
A**2

array([ 16,  64, 144])

In [29]:
np.sqrt(A)

array([2.        , 2.82842712, 3.46410162])

In [30]:
np.log(A)

array([1.38629436, 2.07944154, 2.48490665])

In [31]:
np.exp(A)

array([5.45981500e+01, 2.98095799e+03, 1.62754791e+05])

In [ ]:
# need to use a for loop to do these operations in lists